# Generated by Django 4.1.1 on 2022-09-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varnaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField()),
                ('sepal_width', models.FloatField()),
                ('petal_length', models.FloatField()),
                ('petal_width', models.FloatField()),
                ('classification', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Userreg',
        ),
    ]
